### ISSUE TITLE
有没有什么办法可以让它从一个图片生成？

### ISSUE THREAD

**Issue by purofle** [Kyant2021/MonetRust#1]

**Comment by Kyant2021** [comment]
您可以使用 K-means clustering 算法获取图片主色

**Comment by purofle** [comment]
好的谢谢


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月6日(周六) 中午12:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Kyant2021/MonetRust] 有没有什么办法可以让它从一个图片生成？ (Issue #1)




 
您可以使用 K-means clustering 算法获取图片主色
 
&mdash;
